Dictionary/Controllers/DictionaryController.cs
using BLL.Services.Interfaces;
using Common.Dto;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Dictionary.Controllers
{
    [Authorize(Roles = "Admin, User")]
    public class DictionaryController : Controller
    {
        private ILanguageService languageService;
        private IDictionaryService dictionaryService;

        public DictionaryController(ILanguageService languageService, IDictionaryService dictionaryService)
        {
            this.languageService = languageService;
            this.dictionaryService = dictionaryService;
        }

        public IActionResult Index()
        {
            ViewBag.Languages = new SelectList(languageService.GetAll(), "Id", "Name");

            return View();
        }

        public IActionResult Translate(TranslateWordDto model)
        {
            if (!ModelState.IsValid)
            {
                return Json(new {success = false, response="Введите правильные данные"});
            }

            var response = dictionaryService.TranslateWord(model);
            if(response==null)
                return Json(new { success = false, response = "В словаре нет подходящего слова" });

            return Json(new {success = true, response });
        }
    }
}

Dictionary/Controllers/LanguagesController.cs
using System.Linq;
using System.Threading.Tasks;
using BLL.Services.Interfaces;
using DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Dictionary.Controllers
{
    [Authorize(Roles = "Admin")]
    public class LanguagesController : Controller
    {
        private ILanguageService languageService;

        public LanguagesController(ILanguageService languageService)
        {
            this.languageService = languageService;
        }

        public IActionResult Index()
        {
            var languages = languageService.GetAll().AsEnumerable();
            return View(languages);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Language language)
        {
            await languageService.Create(language);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await languageService.Delete((int)id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var language = languageService.GetLanguage((int)id);
            return View(language);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Language language)
        {
            await languageService.Update(language);
            return RedirectToAction(nameof(Index));
        }
    }
}

Dictionary/Controllers/WordsController.cs
using System.Linq;
using System.Threading.Tasks;
using BLL.Services.Interfaces;
using DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;

namespace Dictionary.Controllers
{
    [Authorize(Roles = "Admin")]
    public class WordsController : Controller
    {
        private IWordService wordService;
        private ILanguageService languageService;
        private readonly IConfiguration configuration;

        public WordsController(IWordService wordService, ILanguageService languageService, IConfiguration configuration)
        {
            this.wordService = wordService;
            this.languageService = languageService;
            this.configuration = configuration;
        }
        public IActionResult Index(int page = 1)
        {
            var isAjax = Request.Headers["X-Requested-With"] == "XMLHttpRequest";

            var pageSize = int.Parse(configuration.GetSection("WordsPageSize").Value);
            var words = wordService.GetWordsPaging(page, pageSize).AsEnumerable();
            if (isAjax)
            {
                return Ok(words);
            }
            return View(words);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Languages = new SelectList(languageService.GetAll(), "Id", "Name");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Word word)
        {
            await wordService.Create(word);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            wordService.Delete((int)id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.Languages = new SelectList(languageService.GetAll(), "Id", "Name");

            var word = wordService.GetWord((int)id);
            return View(word);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Word word)
        {
            await wordService.Update(word);
            return RedirectToAction(nameof(Index));
        }
    }
}

Dictionary/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dictionary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dictionary</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Words" asp-action="Index">Список слов</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Languages" asp-action="Index">Список языков</a>
                            </li>
                        }
                        @if (User.IsInRole("User"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dictionary" asp-action="Index">Переводчик</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Dictionary - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>